name: action
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Approve Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.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 }}
          number: 1
