apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-deployment
  template:
    metadata:
      labels:
        app: sample-deployment
   spec:
     containers:
    	# when pulling from github packages 
    	- image: docker ghcr.io/josliniyda27/hdfc_ibpsportal:alpine-openjdk     
   spec:
     containers:
      - name: sample-deployment1
        image: hdfc_ibpsportal:alpine-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
