apiVersion: v1
kind: Service
metadata:
  name: my_loadbalancer-svc
spec:
  selector:
    app: sample-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
