name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_PullDockerImages__File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker Images
        run: |
          docker --version
          sudo apt-get remove awscli
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          aws --version
          aws-cli/2.0.30 Python/3.7.3 Linux/4.14.181-142.260.amzn2.x86_64 botocore/2.0.0dev34
          chmod +x PullDockerImages.sh
          ./PullDockerImages.sh
          
     
          
