name: CD_Workflow
on: 
  pull_request:
  #schedule: 
  
   # - cron: '15 10 18 11 5'
  
jobs: 
  push_docker_image_to_github_docker_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS_CLI and DOCKER
        run: |
        
          sudo apt-get install awscli
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker
          aws --version
          docker --version
      - name: Pull Docker Images
        run: |
          sudo docker run hello-world
          chmod +x PullDockerImages.sh
          ./PullDockerImages.sh
          sudo docker images
      
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Re-tag the image with GitHub Container Registry path
        run: |
         
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibpsportal:alpine-openjdk ghcr.io/${{ github.actor }}/hdfc_ibpsportal:alpine-openjdk  
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibps5serviceinstanceejb:sp2 ghcr.io/${{ github.actor }}/hdfc_ibps5serviceinstanceejb:sp2
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibps5serviceinstanceweb:sp2 ghcr.io/${{ github.actor }}/hdfc_ibps5serviceinstanceweb:sp2
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibps5userinstanceejb:sp2 ghcr.io/${{ github.actor }}/hdfc_ibps5userinstanceejb:sp2
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibps5userinstanceweb:sp2 ghcr.io/${{ github.actor }}/hdfc_ibps5userinstanceweb:sp2
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_ibpsnodeserver:alpine ghcr.io/${{ github.actor }}/hdfc_ibpsnodeserver:alpine
         sudo docker tag ${{ secrets.AWS_AccountID }}.dkr.ecr.${{ secrets.AWS_Region }}.amazonaws.com/hdfc_od11.0services:ibps5.0sp2 ghcr.io/${{ github.actor }}/hdfc_od11.0services:ibps5.0sp2
      - name: Push image to GitHub Container Registry
        run: |
            
            docker push ghcr.io/${{ github.actor }}/hdfc_ibpsportal:alpine-openjdk
            docker push ghcr.io/${{ github.actor }}/hdfc_ibps5serviceinstanceejb:sp2
            docker push ghcr.io/${{ github.actor }}/hdfc_ibps5serviceinstanceweb:sp2
            docker push ghcr.io/${{ github.actor }}/hdfc_ibps5userinstanceejb:sp2
            docker push ghcr.io/${{ github.actor }}/hdfc_ibps5userinstanceweb:sp2
            docker push ghcr.io/${{ github.actor }}/hdfc_ibpsnodeserver:alpine
            docker push ghcr.io/${{ github.actor }}/hdfc_od11.0services:ibps5.0sp2
            
  jobs: 
    name: Deploy to Kubernetes Cluster
    needs: push_docker_image_to_github_docker_registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Print Hello
      run: echo "Hello Deployment!" 
    
