name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_PullDockerImages__File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker Images
        run: |
        
          sudo apt-get install awscli
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker
          aws --version
          docker --version
          sudo docker run hello-world
          chmod +x PullDockerImages.sh
          ./PullDockerImages.sh
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GH_REGISTRY }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GitHub Container Registry
        run: |
            IMAGE_ID1=ghcr.io/${{ github.repository_owner }}/354354931217.dkr.ecr.ap-south-1.amazonaws.com/hdfc_od11.0services:ibps5.0sp2        
            docker push $IMAGE_ID1

 
