name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_PullDockerImages__File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker Images
        run: |
          aws --version
          docker --version
          sudo docker run hello-world
          chmod +x PullDockerImages.sh
          ./PullDockerImages.sh
