name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_BAT_File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PullDockerImages.bat File
        run: |
          chmod +x PullDockerImages.bat
          ./PullDockerImages.bat

      









