name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_BAT_File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PullDockerImages.bat File
        run: |
          sudo apt-get install awscli
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get update
          apt-get install containerd=1.3.3-0ubuntu1
          sudo apt install docker.io
          docker --version
          sudo docker run hello-world
          chmod +x PullDockerImages.bat
          ./PullDockerImages.bat
          
