name: BatchFileWorkflow
on:
  pull_request:
  
jobs: 
  Run_PullDockerImages__File:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker Images
        run: |
          sudo apt-get install awscli
          aws --version
          sudo apt-get update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker
          docker --version
          sudo docker run hello-world
          chmod +x PullDockerImages.bat
          ./PullDockerImages.bat
